import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Header";
import CardProvider from "@/Context/CardProvider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const poppins = Poppins({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
});
export const metadata = {
  title: {
    default: " Food App 🍔",
    template: "%s |Food App 🍔",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${poppins.className}antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* header */}
        <Header></Header>
        <main className="px-5 py-8 ">
          <CardProvider>
            {children}
          </CardProvider>
        </main>
      </body>
    </html>
  );
}
