import React from 'react'
import Reviwes from './Reviews'
// metadat
  export const metadata = {
      title: {
          absolute:
          "satisfied user"
    },
    description: "Generated by create next app",
  };
const AllReviews = () => {
  
  return (
    <div>
      <Reviwes></Reviwes>
    </div>
  );
};

export default AllReviews